"""
Story Tool Plugin
=================
Tells a short original story on demand. The story is generated by the stack's
own LLM through the engine's one-shot ``summarize_text`` utility completion,
then spoken verbatim to the caller.

Usage in conversation:
User: "Tell me a bedtime story about a brave little turtle"
LLM: [TOOL:STORY:topic=a brave little turtle,audience=kids,length=short]
"""

import logging
from typing import Any, Dict

from tool_plugins import BaseTool, ToolResult, ToolStatus
from logging_utils import log_event

logger = logging.getLogger(__name__)

_STORY_SYSTEM_PROMPT = (
    "You are a storyteller speaking on a phone call. Your story will be read "
    "aloud by a text-to-speech engine, so write plain spoken prose only: no "
    "markdown, no headings, no lists, no stage directions, and no title. "
    "Tell one original story with a clear beginning, middle, and end. "
    "Keep a short story to about 120 words and a medium story to about "
    "250 words. Make the story age-appropriate for the requested audience. "
    "Output ONLY the story, nothing else."
)

# Approximate word budgets echoed into the request so the model has a target.
_WORD_TARGETS = {"short": 120, "medium": 250}


class StoryTool(BaseTool):
    """Tell a short original story generated by the local LLM."""

    name = "STORY"
    description = ("Tell the caller a short original story, optionally about "
                   "a requested topic")
    enabled = True
    speak_result = True  # informational: the story text is spoken verbatim

    parameters = {
        "topic": {
            "type": "string",
            "description": "What the story should be about (optional)",
            "required": False,
            "default": "",
        },
        "audience": {
            "type": "string",
            "description": "Who the story is for: 'kids' or 'adult'",
            "required": False,
            "default": "kids",
        },
        "length": {
            "type": "string",
            "description": "Story length: 'short' or 'medium'",
            "required": False,
            "default": "short",
        },
    }

    async def execute(self, params: Dict[str, Any]) -> ToolResult:
        engine = getattr(self.assistant, "llm_engine", None)
        if self.assistant is None or engine is None:
            return ToolResult(
                status=ToolStatus.FAILED,
                message="I cannot tell stories right now.",
            )

        topic = str(params.get("topic") or "").strip()
        audience = str(params.get("audience") or "kids").strip().lower()
        if audience not in ("kids", "adult"):
            audience = "kids"
        length = str(params.get("length") or "short").strip().lower()
        if length not in _WORD_TARGETS:
            length = "short"

        request = (
            f"Tell a {length} story, about {_WORD_TARGETS[length]} words, "
            f"for a {audience} audience"
        )
        if topic:
            request += f", about {topic}"
        request += "."

        try:
            text = await engine.summarize_text(_STORY_SYSTEM_PROMPT, request, 30.0)
        except Exception as e:
            logger.error(f"Story generation error: {e}", exc_info=True)
            text = None

        if not text or not text.strip():
            return ToolResult(
                status=ToolStatus.FAILED,
                message="I could not think of a story just now.",
            )

        story = text.strip()
        log_event(logger, logging.INFO,
                  f"Story told ({length}, {audience}, {len(story)} chars)",
                  event="story_told", topic=topic,
                  audience=audience, length=length)

        return ToolResult(
            status=ToolStatus.SUCCESS,
            message=story,
            data={
                "topic": topic,
                "audience": audience,
                "length": length,
                "chars": len(story),
            },
        )
